
project_id = "mwufulzthoqrwbwtvogx"

[functions.get-mapbox-token]
verify_jwt = false

[functions.analytics-ingestion]
verify_jwt = false

[functions.search-optimization]
verify_jwt = false

[functions.fact-harvester]
verify_jwt = false

[functions.bulk-import-processor]
verify_jwt = false
